Waffle/waffle

Source/JNA/pom.xml, Source/JNA/waffle-demo/pom.xml, Source/JNA/waffle-tomcat8/pom.xml
Make build slightly faster.
Cleanup duplicate managed war plugin in demo
Cleanup waffle-jna managemed dependency in demo
Update tomcat 8
=> Update tomcat 8 and other minor build cleanup

Source/JNA/waffle-demo/waffle-spring-filter/pom.xml, Source/JNA/waffle-demo/waffle-spring-form/pom.xml, Source/JNA/waffle-distro/pom.xml, Source/JNA/waffle-jetty/pom.xml, Source/JNA/waffle-shiro/pom.xml, Source/JNA/waffle-spring-security3/pom.xml, Source/JNA/waffle-spring-security4/pom.xml, Source/JNA/waffle-tests/pom.xml, Source/JNA/waffle-tomcat6/pom.xml, Source/JNA/waffle-tomcat7/pom.xml, Source/JNA/waffle-tomcat8/pom.xml
This reverts commit 57ba68e9e8f7eb03f8eea5a050fd93358e4d9ab8.
=> Revert "Use ${project.version} throughout."

Source/JNA/pom.xml, Source/JNA/waffle-demo/pom.xml, Source/JNA/waffle-demo/waffle-filter/pom.xml, Source/JNA/waffle-demo/waffle-form/pom.xml, Source/JNA/waffle-demo/waffle-jaas/pom.xml, Source/JNA/waffle-demo/waffle-mixed-post/pom.xml, Source/JNA/waffle-demo/waffle-mixed/pom.xml, Source/JNA/waffle-demo/waffle-negotiate/pom.xml, Source/JNA/waffle-demo/waffle-spring-filter/pom.xml, Source/JNA/waffle-demo/waffle-spring-form/pom.xml, Source/JNA/waffle-distro/pom.xml, Source/JNA/waffle-jetty/pom.xml, Source/JNA/waffle-jna/pom.xml, Source/JNA/waffle-shiro/pom.xml, Source/JNA/waffle-spring-security2/pom.xml, Source/JNA/waffle-spring-security3/pom.xml, Source/JNA/waffle-spring-security4/pom.xml, Source/JNA/waffle-tests/pom.xml, Source/JNA/waffle-tomcat5/pom.xml, Source/JNA/waffle-tomcat6/pom.xml, Source/JNA/waffle-tomcat7/pom.xml, Source/JNA/waffle-tomcat8/pom.xml
=> Resetting me to 1.7.4

Source/JNA/pom.xml
Plus force override of version because sonatype version is placed
incorrectly exposing a maven bug.
=> Fix plugin lifecycle mapping and add enforce plugin

.travis.yml, Source/JNA/pom.xml, Source/JNA/waffle-tomcat8/pom.xml
coveralls attempts to run but has other issues.  will be addressing in a later pull request.
=> Fix coveralls and update plugins

Docs/GettingStartedWithWaffleAPI.md, Docs/ServletSingleSignOnSecurityFilter.md, Docs/SettingUpDevelopmentEnvironment.md, Docs/tomcat/TomcatMixedSingleSignOnAndFormAuthenticatorValve.md, Docs/tomcat/TomcatSingleSignOnValve.md, Docs/tomcat/TomcatWindowsLoginJAASAuthenticator.md, Source/WindowsAuthProviderUnitTests/WindowsAuthProviderUnitTests.csproj, Source/WindowsAuthProviderUnitTests/WindowsSecurityContextUnitTests.cs, Waffle.proj, bootstrap.cmd, build.cmd
Fixes #350 
Updates nunit to 3.2.1
Updates wix to 3.10
Updates documentation info where version numbers listed
=> [nunit] Update .net libraries

CHANGELOG.md, Source/JNA/waffle-tomcat6/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat7/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat8/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat85/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat9/src/main/java/waffle/apache/NegotiateAuthenticator.java
=> Fixed security token leak after a successful authentication in Tomcat

Docs/FAQ.md
=> FAQ: ClassDefNotFoundException, classes moved JAR

Docs/tomcat/TomcatMixedSingleSignOnAndFormAuthenticatorValve.md
=> Fix instructions about waffle-tomcat JAR placement

Source/JNA/waffle-tomcat85/pom.xml
Missed this in last series of updates - thanks versioneyes :)
=> [pom] Update tomcat85 to 8.5.4

.travis.yml, Source/JNA/pom.xml, Source/JNA/waffle-distro/pom.xml, pom.xml, travis/after_success.sh, travis/script.sh
issue #411 fixed by this and #412
=> [ci] Rework build process including tomcat9 in jdk8 build/distro

travis/script.sh
=> [ci] Try quotes around coverity scan branch

Source/JNA/waffle-demo/waffle-filter/pom.xml, Source/JNA/waffle-demo/waffle-form/pom.xml, Source/JNA/waffle-demo/waffle-jaas/pom.xml, Source/JNA/waffle-demo/waffle-mixed-post/pom.xml, Source/JNA/waffle-demo/waffle-mixed/pom.xml, Source/JNA/waffle-demo/waffle-negotiate/pom.xml, Source/JNA/waffle-demo/waffle-spring-filter/pom.xml, Source/JNA/waffle-demo/waffle-spring-form/pom.xml, Source/JNA/waffle-jna/pom.xml, Source/JNA/waffle-spring-security3/pom.xml, Source/JNA/waffle-tests/pom.xml, Source/JNA/waffle-tests/src/main/java/waffle/mock/http/SimpleHttpResponse.java
Only code needing a modification is the test module which isn't used
outside of testing.
=> [servlet3.1] Upgrade to servlet 3.1.0 as its use is provided and we are on java 7

Source/JNA/pom.xml
=> [pom] Update maven-fluido-skins to 1.6

Source/JNA/waffle-distro/pom.xml, Source/JNA/waffle-distro/src/assembly/assembly.xml, Source/JNA/waffle-spring-security3/pom.xml, Source/JNA/waffle-spring-security4/pom.xml
=> Rework spring dependencies so demos work out of the box - Fixes #374

Source/JNA/waffle-jna/src/main/java/waffle/util/WaffleInfo.java, Source/JNA/waffle-jna/src/main/java/waffle/windows/auth/impl/WindowsSecurityContextImpl.java, Source/JNA/waffle-spring-security3/src/main/java/waffle/spring/WindowsAuthenticationProvider.java, Source/JNA/waffle-spring-security4/src/main/java/waffle/spring/WindowsAuthenticationProvider.java, Source/JNA/waffle-tomcat6/src/main/java/waffle/apache/MixedAuthenticator.java, Source/JNA/waffle-tomcat6/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat7/src/main/java/waffle/apache/MixedAuthenticator.java, Source/JNA/waffle-tomcat7/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat8/src/main/java/waffle/apache/MixedAuthenticator.java, Source/JNA/waffle-tomcat8/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat85/src/main/java/waffle/apache/MixedAuthenticator.java, Source/JNA/waffle-tomcat85/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat9/src/main/java/waffle/apache/MixedAuthenticator.java, Source/JNA/waffle-tomcat9/src/main/java/waffle/apache/NegotiateAuthenticator.java
*mixed authentication was missing similar code which would otherwise expose the Win32Exception so that has been fixed.
=> [tomcat] Restructure negotiate/mixedAuthentication so try/catch do not next*

CHANGELOG.md, Source/JNA/src/site/markdown/README.md, Source/JNA/waffle-distro/pom.xml, Source/JNA/waffle-distro/src/assembly/LICENSE-caffeine.txt, Source/JNA/waffle-distro/src/assembly/LICENSE-jna.txt, Source/JNA/waffle-distro/src/assembly/LICENSE-logback.txt, Source/JNA/waffle-distro/src/assembly/LICENSE-slf4j.txt, Source/JNA/waffle-distro/src/assembly/assembly.xml
...plus missed README update and CHANGELOG update.
=> Add licenses for third party libraries in distro

Source/JNA/pom.xml
Almost all are properties now.  This is the bulk.  Remainder will come later.
=> Update htmlcompressor, dependency check, and migrate to properties for plugin versions

Source/JNA/pom.xml, Source/JNA/waffle-jna/pom.xml, Source/JNA/waffle-jna/src/test/java/waffle/jaas/WindowsLoginModuleTest.java, Source/JNA/waffle-shiro/pom.xml, Source/JNA/waffle-shiro/src/test/java/waffle/shiro/negotiate/NegotiateAuthenticationFilterTest.java
Update junit to 5.5.2
Update jmockit to 1.48
Add powermock to replace jmockit 'Deencapsulation' which was removed from jmockit
=> Upgrade testing harness

Source/JNA/pom.xml
we have not released a site in 2 years...null pointer issue with javadocs.
=> Rework overall pom configuration and patch for javadoc generation

Docs/Troubleshooting.md
- Link to web.archive.org (since the download is offline)
- Add link details
=> docs(Troubleshooting): link fix

Docs/FAQ.md, Docs/faq/CustomCache.md, Source/JNA/waffle-jna/src/main/java/waffle/util/cache/Cache.java, Source/JNA/waffle-jna/src/main/java/waffle/util/cache/CacheSupplier.java, Source/JNA/waffle-jna/src/main/java/waffle/util/cache/CaffeineCache.java, Source/JNA/waffle-jna/src/main/java/waffle/util/cache/CaffeineCacheSupplier.java, Source/JNA/waffle-jna/src/main/java/waffle/windows/auth/impl/WindowsAuthProviderImpl.java, Source/JNA/waffle-jna/src/main/resources/META-INF/services/waffle.waffle.util.cache.CacheSupplier
This allows users of this library to provide a different implementaiton of the cache, e.g., based on Guava or with a database backend.
=> Implement ServiceLoader for creating a cache

Docs/spring/SpringSecuritySingleSignOnFilter.md
Describe a way to configure Mixed SSO and form authentication with Waffle in spring-security
=> Mixed single-SignOn and form authentication

NOTICE
=> Update license in NOTICE

CHANGELOG.md, Source/JNA/waffle-demo/waffle-spring-boot-filter2/pom.xml, Source/JNA/waffle-jetty/src/test/java/waffle/jetty/StartEmbeddedJettyValidateNTLMGroup.java, Source/JNA/waffle-spring-security5/pom.xml
code change is non risk as test code.
=> Small cleanup and adjustment for dropping back to slf4j

Source/JNA/waffle-demo/waffle-spring-boot-filter2/pom.xml
This is properly handled on the project now.
=> [pom] Remove extra items from waffle spring boot filter2

Source/JNA/waffle-distro/pom.xml, Source/JNA/waffle-spring-boot2/pom.xml
Unsure why when the modules resolve to latest, getting tricky, force distro up.
=> [pom] Move to log4j2 bom and add a patch in distro

Source/JNA/waffle-demo/README.md, Source/JNA/waffle-demo/waffle-jaas/README.md, Source/JNA/waffle-demo/waffle-mixed-post/README.md, Source/JNA/waffle-demo/waffle-mixed-post/pom.xml, Source/JNA/waffle-demo/waffle-mixed/README.md, Source/JNA/waffle-demo/waffle-mixed/pom.xml, Source/JNA/waffle-demo/waffle-negotiate/README.md, Source/JNA/waffle-demo/waffle-negotiate/pom.xml
notes where not yet complete in attempt to make it easier to use these with cargo plugin.
=> Supporting documentation for demos

Source/JNA/waffle-jna-jakarta/src/main/java/waffle/util/cache/Cache.java, Source/JNA/waffle-jna/src/main/java/waffle/util/cache/Cache.java
WIP, not ready for merge yet.
Partial fix for #2522 - currently a code example for review before duplicating for other packages.
TODO:
* Polish code
* Propagate change to other package (waffle-jna/src/main/java/waffle/util/cache/Cache.java)
* Add link to the custom cache FAQ page in log message
* Add text to the custom cache FAQ page detailing thread.setContextClassLoader(CacheSupplier.class.getClassLoader()) workaround, and mentioning the log message text for searching
=> Fixes for #2522

.github/workflows/coveralls.yaml
within windows I can run this using same data so not sure what is going on here.
=> [gha] Run coveralls in debug to figure out issue
