Waffle/waffle

Source/JNA/waffle-tomcat8/src/main/java/waffle/apache/MixedAuthenticator.java
For the Tomcat 8 MixedAuthenticator, a dummy LoginConfig object was being created and used instead of pulling LoginConfig out of the context.
=> Tomcat 8 MixedAuthenticator bug

Source/JNA/pom.xml, Source/JNA/src/site/markdown/README.md, Source/JNA/waffle-jetty/pom.xml, Source/JNA/waffle-spring-security3/src/main/java/waffle/spring/DelegatingNegotiateSecurityFilter.java, Source/JNA/waffle-spring-security4/src/main/java/waffle/spring/DelegatingNegotiateSecurityFilter.java, Source/JNA/waffle-tests/pom.xml, Source/JNA/waffle-tests/src/test/java/waffle/util/AuthorizationHeaderTests.java, Source/JNA/waffle-tomcat8/pom.xml, Source/JNA/waffle-tomcat8/src/main/java/waffle/apache/GenericWindowsPrincipal.java, Source/JNA/waffle-tomcat8/src/main/java/waffle/apache/MixedAuthenticator.java
Keeping plugins / dependencies up-to-date
Replaced catch-exception library which had two issues.  1) it was compiled with java 7 which sort of makes a potential problem since we use java 6.  2) It relies on older jmockit and attempts to that library updated while mostly a success didn't solve core issue.  That said, moving to another much more limble library that only has assertj as a dependency which we use and requires no special considerations.  Code is also slightly cleaner.  So as of this pull request, we are using all the latest dependencies across the board that are part of this project.
=> Maintainance and Unit test library change

CHANGELOG.md, Source/JNA/waffle-tomcat6/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat6/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java, Source/JNA/waffle-tomcat7/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat7/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java, Source/JNA/waffle-tomcat8/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat8/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java
A fix to capture tomcat 6, 7, and 8 negotiate authenticator
Win32Exception which started occurring around June 2015 per issue #107.
Around that time Exception was switched out for IOException which
allowed Win32Exception to occur.  Now catch that and perform same
actions as IOException.  Left original unit tests capturing fall through
and added new check as this shows Negotiate, NTLM where the comma was
normally expected to be a space.  This does fix the condition but I'm
not 100% certain this is correct from unit test side.
=> [issue #203] Catch Win32Exception and make 401

CHANGELOG.md, Source/JNA/waffle-jna/src/main/java/waffle/windows/auth/impl/WindowsAuthProviderImpl.java, Source/JNA/waffle-jna/src/main/java/waffle/windows/auth/impl/WindowsSecurityContextImpl.java, Source/JNA/waffle-tests/src/test/java/waffle/servlet/NegotiateSecurityFilterTests.java, Source/JNA/waffle-tests/src/test/java/waffle/windows/auth/WindowsAuthProviderTests.java, Source/JNA/waffle-tomcat6/src/test/java/waffle/apache/MixedAuthenticatorTests.java, Source/JNA/waffle-tomcat6/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java, Source/JNA/waffle-tomcat7/src/test/java/waffle/apache/MixedAuthenticatorTests.java, Source/JNA/waffle-tomcat7/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java, Source/JNA/waffle-tomcat8/src/test/java/waffle/apache/MixedAuthenticatorTests.java, Source/JNA/waffle-tomcat8/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java
I noticed that the handle count of the LSASS process would continuously go up on servers using Waffle. Stopping the Java process would result in the handle count to immediately drop back to a normal value.
After a bit of digging I found out that the `WindowsCredentialsHandleImpl` allocated in `acceptSecurityToken` was never disposed, causing the leak. To fix that, I've arranged for this object lifetime to be determined by the associated `WindowsSecurityContextImpl`, since everywhere I could find the server credentials always end up tightly bound to one of those --- that is unless someone is calling `WindowsAuthProviderImpl.getCurrent` directly, but in this case the caller is responsible of calling `dispose` on it.
With this modification the handle count of both the server process and …
=> Fix handle leak in LSASS

Source/JNA/pom.xml
standard test files do not end with 's' on Test.  As such some tests were not running.  Will rename all test files at a later time.
=> Make sure we include standard test files and update jmockit

CHANGELOG.md, Source/JNA/waffle-jna/src/main/java/waffle/util/AuthorizationHeader.java, Source/JNA/waffle-jna/src/main/java/waffle/util/SPNegoMessage.java, Source/JNA/waffle-jna/src/test/java/waffle/util/SPNegoMessageTests.java, Source/JNA/waffle-tests/src/test/java/waffle/util/AuthorizationHeaderTests.java
Only NegTokenInit is similar to NTLM type 1 message, NegTokenArg occurs only when there is already an ongoing negotiation. Cleaned up method names a bit also to reflect this.
This should fix the first problem in issue #167.
=> Don't allow SPNEGO NegTokenArg to start re-authentication.

bootstrap.cmd
Fixes #348 
Quick fix solution is to leave us on version 2.6.4 of nunit until we can upgrade without affecting users currently trying to build application.
=> [nunit] Set nuget version to use as 2.6.4

Source/JNA/waffle-tomcat9/pom.xml, Source/JNA/waffle-tomcat9/src/main/java/waffle/apache/MixedAuthenticator.java, Source/JNA/waffle-tomcat9/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat9/src/test/java/waffle/apache/MixedAuthenticatorTests.java, Source/JNA/waffle-tomcat9/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java
As of now, tomcat 9 module no longer requires guava at all.
=> Update tomcat 9 and use standard java 8 instead of guava

CHANGELOG.md, Source/JNA/waffle-spring-security3/src/main/java/waffle/spring/DelegatingNegotiateSecurityFilter.java, Source/JNA/waffle-spring-security4/src/main/java/waffle/spring/DelegatingNegotiateSecurityFilter.java, Source/JNA/waffle-spring-security4/src/test/java/waffle/spring/DelegatingNegotiateSecurityFilterTest.java, Source/JNA/waffle-spring-security4/src/test/java/waffle/spring/handlers/CustomAccessDeniedHandler.java, Source/JNA/waffle-spring-security4/src/test/resources/springTestFilterBeans.xml
In case that user wants to just add handlers but not to provide a custom authentication ,the auth object is not saved
this will fix it
=> Added default setter for authentication

Source/JNA/waffle-tomcat85/pom.xml, Source/JNA/waffle-tomcat85/src/main/java/waffle/apache/MixedAuthenticator.java, Source/JNA/waffle-tomcat85/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat85/src/test/java/waffle/apache/WaffleAuthenticatorBaseTest.java, Source/JNA/waffle-tomcat9/pom.xml, Source/JNA/waffle-tomcat9/src/main/java/waffle/apache/MixedAuthenticator.java, Source/JNA/waffle-tomcat9/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat9/src/test/java/waffle/apache/WaffleAuthenticatorBaseTest.java
Fixes #389 
The expectation of this fix is that compilation is performed against new code base but we still use the older method invocations and as such should support old and new without issues.
=> Update tomcat 8.5 and 9 with fixes for api changes Fixes #389

Source/JNA/waffle-tests/src/test/java/waffle/jaas/WindowsLoginModuleTests.java
Originally I didn't catch this as I had additinally updated mockito and I had thought the issues were related to mockito update.  After reverting mockito out so I could do other work, it became evident #397 broke the waffle-test module.  After reviewing the work, it was rather easy to clean that up.
=> [waffle-tests] As a result of PR397, waffle-tests required changes

Source/JNA/waffle-tomcat6/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java, Source/JNA/waffle-tomcat7/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java, Source/JNA/waffle-tomcat8/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java, Source/JNA/waffle-tomcat85/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java, Source/JNA/waffle-tomcat9/src/test/java/waffle/apache/NegotiateAuthenticatorTests.java
tomcat code was corrected so bug that was seen in test cases no longer
is present.  Removing unnecessary try/catch so we don't re-introduct
issues later.
=> [tests] Cleanup tests that no longer require try / catch logic

Source/JNA/waffle-spring-security3/src/main/java/waffle/spring/WindowsAuthenticationProvider.java, Source/JNA/waffle-spring-security4/src/main/java/waffle/spring/WindowsAuthenticationProvider.java
Fixes Waffle/waffle#408
The try/catch/re-throw was removed here:
https://github.com/Waffle/waffle/commit/c9c01a306833b589008b86022156b12b18e1b024#diff-150290ffe737db29594cc307562faeceL76
@hazendaz Can you comment on why this was removed?
=> [spring] Re-throw Win32Exception as AuthenticationServiceException - Fixes #408

Source/JNA/pom.xml, Source/JNA/waffle-jna/pom.xml, Source/JNA/waffle-jna/src/main/java/waffle/windows/auth/impl/WindowsAuthProviderImpl.java
Set the compiler to 1.8 (defaults to 1.5). This does not change code patterns, as still valid and style is a team choice. Switched from Guava's cache to Caffeine as requested.
=> Upgrade to Java 8 - using caffeine

Waffle.nuspec
Pull request related to #267 to add Waffle as nuget package, please check the values set in Waffle.nuspec as may not be correct including version number.  Also ensure the file source node is correct, I ran a local build and pointed it at the directory where dll is built.
The following steps are required to publish on Nuget gallery.  Instructions taken from [here](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package)
- nuget  pack Waffle.nuspec
- Create account at [nuget](https://www.nuget.org/users/account/LogOn?returnUrl=%2F) and generate nuget api key here 
- nuget push  Waffle.1.8.4.nupkg **<Generated api key here>** -Source https://www.nuget.org/api/v2/package
To test create a local project and install Waffle package from nuget, if you want to test a local …
=> added Waffle.nuspec

Docs/FAQ.md
Added Troubleshooting story where I struggled to control the waffle debug information logs while running it in windows with Tomcat server. The log level was controlled to error or exception level after placing the logback configuration file under tomcat lib folder. The configuration file should be placed where waffle jar files are available.
This was night mare issue when debug log information makes your log file size in #GB and it shouts down the tomcat server after running for longer period.
=> Added troubleshooting story to disable debug log

Source/JNA/waffle-tomcat7/src/main/java/waffle/apache/MixedAuthenticator.java, Source/JNA/waffle-tomcat7/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat7/src/main/java/waffle/apache/WaffleAuthenticatorBase.java, Source/JNA/waffle-tomcat7/src/test/java/waffle/apache/MixedAuthenticatorTests.java, Source/JNA/waffle-tomcat8/src/main/java/waffle/apache/MixedAuthenticator.java, Source/JNA/waffle-tomcat8/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat8/src/main/java/waffle/apache/WaffleAuthenticatorBase.java, Source/JNA/waffle-tomcat8/src/test/java/waffle/apache/MixedAuthenticatorTests.java, Source/JNA/waffle-tomcat85/src/main/java/waffle/apache/MixedAuthenticator.java, Source/JNA/waffle-tomcat85/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat85/src/main/java/waffle/apache/WaffleAuthenticatorBase.java, Source/JNA/waffle-tomcat85/src/test/java/waffle/apache/MixedAuthenticatorTests.java, Source/JNA/waffle-tomcat9/src/main/java/waffle/apache/MixedAuthenticator.java, Source/JNA/waffle-tomcat9/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat9/src/main/java/waffle/apache/WaffleAuthenticatorBase.java, Source/JNA/waffle-tomcat9/src/test/java/waffle/apache/MixedAuthenticatorTests.java
refering:
https://github.com/Waffle/waffle/issues/561
my main target is it to get the roles not directly by the windows roles but by a further mechanism that gets some roles from a database query using the current windowsIdentity as a query parameter
=> Custom instances of GenericPrincipal in WaffleAuthenticatorBase

CHANGELOG.md, Source/JNA/waffle-jna/src/main/java/waffle/windows/auth/impl/WindowsAuthProviderImpl.java, Source/JNA/waffle-tomcat6/src/main/java/waffle/apache/MixedAuthenticator.java, Source/JNA/waffle-tomcat6/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat6/src/main/java/waffle/apache/WaffleAuthenticatorBase.java, Source/JNA/waffle-tomcat7/src/main/java/waffle/apache/WaffleAuthenticatorBase.java, Source/JNA/waffle-tomcat8/src/main/java/waffle/apache/WaffleAuthenticatorBase.java, Source/JNA/waffle-tomcat85/src/main/java/waffle/apache/WaffleAuthenticatorBase.java, Source/JNA/waffle-tomcat9/src/main/java/waffle/apache/WaffleAuthenticatorBase.java
Fixes issue #194 and resolves pull request #196 for all tomcats.  This is mostly the same as original but I called out JNA to a static as we did internally set the time to 30 seconds then I used that throughout so we were not repeating ourselves.  Also in tomcat6, we never called tomcats lifecycle.  I'm sure there was reason for this.  The tests locked when doing that.  I'm sure they eventually came back but because this PR does nothing to address that original design, I opted to not apply that and added comments instead.  The end result is a lot less code changes.
Formatting on how we allign properties is a mess when new items are added which is something I learned over the past few years.  I plan to address that on master in near future.
=> Pr/196 - Externally configure continueContextsTimeout for tomcat(s)

Source/JNA/waffle-tomcat7/src/main/java/waffle/apache/MixedAuthenticator.java, Source/JNA/waffle-tomcat7/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat7/src/main/java/waffle/apache/WaffleAuthenticatorBase.java, Source/JNA/waffle-tomcat7/src/test/java/waffle/apache/MixedAuthenticatorTests.java, Source/JNA/waffle-tomcat8/src/main/java/waffle/apache/MixedAuthenticator.java, Source/JNA/waffle-tomcat8/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat8/src/main/java/waffle/apache/WaffleAuthenticatorBase.java, Source/JNA/waffle-tomcat8/src/test/java/waffle/apache/MixedAuthenticatorTests.java, Source/JNA/waffle-tomcat85/src/main/java/waffle/apache/MixedAuthenticator.java, Source/JNA/waffle-tomcat85/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat85/src/main/java/waffle/apache/WaffleAuthenticatorBase.java, Source/JNA/waffle-tomcat85/src/test/java/waffle/apache/MixedAuthenticatorTests.java, Source/JNA/waffle-tomcat9/src/main/java/waffle/apache/MixedAuthenticator.java, Source/JNA/waffle-tomcat9/src/main/java/waffle/apache/NegotiateAuthenticator.java, Source/JNA/waffle-tomcat9/src/main/java/waffle/apache/WaffleAuthenticatorBase.java, Source/JNA/waffle-tomcat9/src/test/java/waffle/apache/MixedAuthenticatorTests.java
backport to 1.8.x branch as-is with fixes for java 7 usage.  Will do more later as pieces are missing from tomcat 7 and 8 in general and we need to back port for 6.
=> Custom instances of GenericPrincipal in WaffleAuthenticatorBase (#571)

Docs/FAQ.md, Docs/faq/400BadRequest.md, Docs/faq/ADGroupsSpringSecurity.md, Docs/faq/AJP.md, Docs/faq/AJP_attach1.txt, Docs/faq/AP_ERR_MODIFIED.md, Docs/faq/BasicPopup.md, Docs/faq/ClassNotFoundJBoss.md, Docs/faq/ClassNotFoundTomcat.md, Docs/faq/JBossLogging.md, Docs/faq/LoadBalancer.md, Docs/faq/NegotiateFailsWith401.md, Docs/faq/NotAcceptingMultipartData.md, Docs/faq/PassPromptInsteadOfSSO.md, Docs/faq/ServiceUserAsRemoteUser.md, Docs/faq/SessionTimeouts.md, Docs/faq/TempFileFailed.md, Docs/faq/UnsatisfiedLinkerErrorjnadispatch.md
=> Pull discussion from CodePlex to markdown docs

Docs/ServletSingleSignOnSecurityFilter.md, Docs/faq/AtlassianJIRA.md, Source/JNA/waffle-jna/src/main/java/waffle/servlet/NegotiateSecurityFilter.java
Add more detailed instructions for JIRA
=> Update for use with Atlassian JIRA

CHANGELOG.md, Docs/ServletSingleSignOnSecurityFilter.md, Source/JNA/waffle-jna/src/main/java/waffle/servlet/NegotiateSecurityFilter.java, Source/JNA/waffle-jna/src/main/java/waffle/util/AuthorizationHeader.java
This applies all changes of Pr/630 with exception to the browser being forced to windows only.
=> Pr/630 - DisableSso flag, Delete option, skip when running on non windows

Source/JNA/waffle-distro/src/assembly/assembly.xml
previously we split war vs jar.  Since spring boot are jars, we need extra logic to ensure it drops to correct folder.
=> [assembly] Adjustments for distro on springboot

Docs/MavenReleaseGuide.md, Docs/ServletSingleSignOnSecurityFilter.md, Docs/spring/DelegatingSpringSecuritySingleSignOnFilter.md, Docs/spring/SpringSecurityAuthenticationProvider.md, Docs/spring/SpringSecuritySingleSignOnFilter.md, Docs/tomcat/TomcatMixedSingleSignOnAndFormAuthenticatorValve.md, Docs/tomcat/TomcatSingleSignOnValve.md, Docs/tomcat/TomcatWindowsLoginJAASAuthenticator.md, Docs/wildfly/WildFlySecurityDomain.md, Source/JNA/waffle-demo/pom.xml, Source/JNA/waffle-demo/waffle-spring-boot-filter/pom.xml, Source/JNA/waffle-demo/waffle-spring-boot-filter2/pom.xml
demos have logback configuration but don't necessarily have logback added.  This also makes it more clear as to what version is used with springboot as we now firmly define the older logback releases.
=> Update docs / Add logback to the demos

Source/JNA/waffle-tomcat7/src/test/java/waffle/apache/MixedAuthenticatorTests.java
… via redirect
This fixes #855 
The changes that were made to allow for redirect during negotiate now failed only in tomcat7 module due to legacy way tomcat handled login and the fact that since no prior redirect we were intentially sending null as the login config.  This did not affect testing in tomcat85 or tomcat9 as the logic is different and there is no additional called in loginConfig at that point (thus no null).  The originally testing for #800 was done with tomcat9 thus the issue was not immediately noticed and the tests only run on windows and we generally only pay attention to travis-ci results.  This resolution now allows us to move to release the repo again to incorporate enhanced processing and better user experience.
=> [tests] Add loginConfig for tomcat7 mixed auth test as it is now used…fixes #855

Source/JNA/waffle-demo/waffle-spring-boot-filter/pom.xml, Source/JNA/waffle-demo/waffle-spring-boot-filter2/pom.xml, Source/JNA/waffle-jna/pom.xml, Source/JNA/waffle-spring-boot/pom.xml, Source/JNA/waffle-spring-boot2/pom.xml, Source/JNA/waffle-spring-security4/pom.xml, Source/JNA/waffle-spring-security5/pom.xml
Jna is too critical for waffle to not be in dependency management.  Moved there overall.  Update spring modules.  Start controlling versions on now unsupported spring boot 1 since spring 4 is still going to be supported until end of 2020.  We will continue to support it as well for legacy usage.  Ensure vulnerability free versions showing up in the build in that case.
=> Jna Moved to Dependency Management, spring updates, spring boot 1 overrides

Docs/Troubleshooting.md
`setspn` needs to be invoked for the machine name as well as the virtual-host configured in the webserver.
Ref: https://support.microsoft.com/en-gb/help/929650/how-to-use-spns-when-you-configure-web-applications-that-are-hosted-on
=> docs(Troubleshooting): setspn machine/virtual-host

.travis.yml, CHANGELOG.md, Source/JNA/waffle-jna-jakarta/src/main/java/waffle/jaas/GroupPrincipal.java, Source/JNA/waffle-jna/src/main/java/waffle/jaas/GroupPrincipal.java
group has been deprecated for years, it's deleted from newer jdks.  Since we only use that interface but otherwise provide the implementation, simply stop using it and continue as is.  This is untested as far as jdk 14/15 goes but all tests do pass.  Additional testing will be confirmed prior to release.
=> [jdk] Stop using deprecated interface and just directly configure group and update changelog

Source/JNA/waffle-demo/waffle-spring-filter/src/main/webapp/WEB-INF/waffle-filter.xml
When starting the sample application, the following error message appeared: java.lang.IllegalArgumentException: Failed to evaluate expression 'IS_AUTHENTICATED_FULLY'
The problem is caused by the fact that Spring Security 4 is using the expression syntax by default. Thus in the waffle-filter.xml configuration "IS_AUTHENTICATED_FULLY" needs to be replaced by "fullyAuthenticated".
=> waffle-spring-filter: spring security 4 compatibility

CHANGELOG.md, Source/JNA/waffle-spring-security5/src/main/java/waffle/spring/NegotiateSecurityFilter.java
The same fix was done for `waffle.servlet.NegotiateSecurityFilter` and `waffle.jaas.WindowsLoginModule` in commit 8339251e.
=> Dispose of guest WindowsIdentity when guest login is disabled

.github/dependabot.yml, Source/JNA/pom.xml, Source/JNA/waffle-demo/pom.xml, Source/JNA/waffle-demo/waffle-spring-boot-filter2/pom.xml, Source/JNA/waffle-distro/pom.xml
Versions 1.8.x and 2.x are incompatible with older versions. The vast majority of libraries are still using 1.7.x because the 2.x releases are still in beta.
This PR downgrades SLF4J to the latest 1.7.x and updates the dependabot configuration to prevent upgrades to the 1.8.x and 2.x versions.
=> Downgrade slf4j to 1.7.x

Docs/GettingStartedWithWaffleAPI.md, Docs/MavenReleaseGuide.md, Docs/ServletSingleSignOnSecurityFilter.md, Docs/spring/SpringSecurityAuthenticationProvider.md, Docs/spring/SpringSecuritySingleSignOnFilter.md, Docs/tomcat/TomcatMixedSingleSignOnAndFormAuthenticatorValve.md, Docs/tomcat/TomcatSingleSignOnValve.md, Docs/tomcat/TomcatWindowsLoginJAASAuthenticator.md, Docs/wildfly/WildFlySecurityDomain.md
these get out of sync often, just call out looking at distro for specific versions.
update spring 4 to 5.
update java usage to build and maven usage to build
=> [docs] Remove version strings and point to distro instead

.github/workflows/ci.yaml, Source/JNA/pom.xml
prior setup allowed any 11 or better.  intent was to lock it down to what we confirmed works while getting rid of old builds from github actions.  Thus fix to lock ranges to any 11, any 17, any 19, and any 20 and block all others.
=> [pom] Configure required java version for enforcer more strictly

Docs/faq/CustomCache.md
Add documentation for resolving the CacheSupplier error message, including use cases where specifying the CacheSupplier implementation via META-INF/services just doesn't work (in one example, in a plugin environment)
=> Update the FAQ for using a custom cache implementation
